{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autofile.secretName" . }}
  labels:
    {{- include "autofile.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.database.mode "external" }}
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  REDIS_URL: {{ include "autofile.redisURL" . | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  {{- if include "autofile.awsCredentialsEnabled" . }}
  AWS_ACCESS_KEY_ID: {{ include "autofile.awsAccessKeyID" . | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ include "autofile.awsSecretAccessKey" . | b64enc | quote }}
  {{- end }}
{{- end }}
