apiVersion: v1
kind: Service
metadata:
  name: {{ include "autofile.api.fullname" . }}
  labels:
    {{- include "autofile.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "autofile.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: http
