{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autofile.secretName" . }}
  labels:
    {{- include "autofile.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  REDIS_URL: {{ include "autofile.redisURL" . | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
{{- end }}
