{{- if include "autofile.valkey.enabledWithAuth" . }}
{{- $secretName := include "autofile.valkey.usersSecretName" . }}
{{- $passwordKey := include "autofile.valkey.defaultPasswordKey" . }}
{{- $password := include "autofile.valkey.defaultPassword" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "autofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $passwordKey | quote }}: {{ $password | quote }}
{{- end }}
