apiVersion: v2
name: autofile
description: Autofile API and UI deployment
type: application
version: 0.3.1
appVersion: v0.3.1
keywords:
  - edms
  - dms
  - autofile
maintainers:
  - name: joekhoobyar
    email: fourheads@gmail.com
dependencies:
  - name: valkey
    version: 0.11.0
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
  - name: rustfs
    version: 1.0.0-rc.3
    repository: https://charts.rustfs.com
    condition: rustfs.enabled
