apiVersion: v2
name: autofile
description: Self-hosted document management application
type: application
version: 0.5.4
appVersion: v0.5.4
home: https://autofile.dev/
sources:
  - https://github.com/joekhoobyar/autofile
icon: https://autofile.dev/assets/favicon.png
keywords:
  - edms
  - dms
  - autofile
  - document-management
  - self-hosted
maintainers:
  - name: joekhoobyar
    email: fourheads@gmail.com
annotations:
  artifacthub.io/license: AGPL-3.0-only
  artifacthub.io/category: storage
  artifacthub.io/links: |
    - name: Documentation
      url: https://autofile.dev/
    - name: Source
      url: https://github.com/joekhoobyar/autofile
    - name: Changelog
      url: https://autofile.dev/changelog/
dependencies:
  - name: valkey
    version: 0.12.0
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
  - name: rustfs
    version: 1.0.0-rc.6
    repository: https://charts.rustfs.com
    condition: rustfs.enabled
