-- Your SQL goes here
ALTER TABLE "users" ADD COLUMN "email" VARCHAR NOT NULL;

CREATE TABLE "cabinets"(
	"id" BIGSERIAL PRIMARY KEY,
	"slug" VARCHAR NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL,
	"description" VARCHAR,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

