[package]
name = "autofile-api"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
argon2 = "0.5"
password-hash = "0.5"
rand_core = "0.6"

diesel = { version = "2", features = ["postgres", "chrono"] }
diesel-async = { version = "0.4.1", features = ["postgres", "async-connection-wrapper"] }
diesel_migrations = "2"

rocket_db_pools = { version = "0.2.0", features = ["diesel_postgres"] }
rocket_cors = "0.6.0"
